---
- name: make Arch comfy
  hosts: localhost

  tasks:
    - name: install core utilities
      become: true
      community.general.pacman:
        name: 
          - base-devel
          - git
          - go
          - inetutils
          - systemd-resolvconf
          - docker
        state: present
        update_cache: true

    - name: install UI packages
      become: true
      ignore_errors: true
      community.general.pacman:
        name: 
          - sway
          - swaybg
          - swayidle
          - xorg-xwayland 
          - swaylock 
          - waybar 
          - noto-fonts-emoji 
          - noto-fonts-emoji 
          - otf-font-awesome 
          - ttf-croscore 
          - mako 
          - ttf-dejavu 
          - ttf-liberation 
          - noto-fonts
        state: present

    - name: install essential tools
      become: true
      ignore_errors: true
      community.general.pacman:
        name: 
          - kitty 
          - firefox 
          - playerctl 
          - lazygit 
          - wl-clipboard
          - jq
          - wireguard-tools
          - neovim
        state: present

    - name: install utilities
      become: true
      community.general.pacman:
        name: 
          - virtualbox 
          - cups 
          - udiskie 
          - nnn 
          - grim 
          - slurp 
          - wofi
          - php
          - chromium
          - fish
        state: present

    - name: clone Yay
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: ~/yay

    - name: install Yay
      ansible.builtin.command:
        chdir: ~/yay
        cmd: makepkg -si --noconfirm

    - name: install daily apps
      become: true
      ignore_errors: true
      community.general.pacman:
        name: 
          - thunderbird
        state: present
    - name: enable systemd-resolved
      become: true
      ansible.builtin.systemd:
        name: systemd-resolved
        state: started
        enabled: yes
    - name: enable docker
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    - name: adding user to groups
      user:
        name: josh
        groups: docker
        append: yes        
    - name: clone cornwall council tools
      ansible.builtin.git:
        repo: 'https://github.com/mewejo/cornwall-council.git'
        dest: /home/josh/cornwall-council

