---
- name: "Update user shell"
  become: yes
  ansible.builtin.user:
    name: josh 
    shell: "/usr/bin/fish"

- name: "Add user to Groups"
  user:
    name: josh
    groups: docker
    append: yes

