---
- name: "Update user shell"
  become: yes
  ansible.builtin.user:
    name: josh 
    shell: "/usr/bin/fish"

- name: "Create Docker group"
  become: yes
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add user to Groups"
  become: yes
  user:
    name: josh
    groups: docker
    append: yes

- name: "Create bin directory"
  ansible.builtin.file:
    path: /home/josh/bin
    state: directory
    mode: '0755'

- name: "Create .ssh directory"
  ansible.builtin.file:
      path: /home/josh/.ssh
      state: directory
      mode: '0700'

- name: "Import SSH keys"
  ansible.builtin.shell:
    cmd: "curl https://github.com/mewejo.keys > /home/josh/.ssh/authorized_keys"

- name: "Set authorized_keys permissions"
  ansible.builtin.file:
    path: /home/josh/.ssh/authorized_keys
    state: file
    mode: '0644'

- name: "Determine if dotfiles are installed"
  register: dotfiles_exist
  stat:
    path: /home/josh/.dotfiles

- name: "Initiate wallpaper"
  when: dotfiles_exist.stat.exists
  ansible.builtin.shell:
    cmd: "/home/josh/.scripts/sway/choose-wallpaper"

- name: "GPG sign all Git commits"
  community.general.git_config:
    name: commit.gpgsign
    value: true
    scope: global
