---
- name: "Update user shell"
  become: yes
  ansible.builtin.user:
    name: josh 
    shell: "/usr/bin/fish"

- name: "Create Docker group"
  become: yes
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add user to Groups"
  become: yes
  user:
    name: josh
    groups: docker
    append: yes

- name: "Create bin directory"
  ansible.builtin.file:
    path: /home/josh/bin
    state: directory
    mode: '0755'

