---
- name: "Flathub repository"
  community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user

- name: "Fedora Flatpak repository"
  community.general.flatpak_remote:
      name: fedora
      state: present
      flatpakrepo_url: oci+https://registry.fedoraproject.org
      method: user

- name: "Remove System Fedora Flatpak repository"
  become: yes
  community.general.flatpak_remote:
    name: fedora
    state: absent
    method: system

- name: "Remove System Flathub repository"
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: absent
    method: system

- name: Install Flathub packages
  community.general.flatpak:
    remote: flathub
    name:
      - org.mozilla.firefox
      - org.mozilla.thunderbird
