---
- name: "Remove Gnome Flatpaks"
  ignore_errors: yes
  become: yes
  community.general.flatpak:
    state: absent
    method: system
    name: "{{ item }}"
  loop:
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Characters
    - org.gnome.Cheese
    - org.gnome.Connections
    - org.gnome.Contacts
    - org.gnome.Evince
    - org.gnome.Extensions
    - org.gnome.Logs
    - org.gnome.Maps
    - org.gnome.NautilusPreviewer
    - org.gnome.TextEditor
    - org.gnome.Weather
    - org.gnome.baobab
    - org.gnome.clocks
    - org.gnome.eog
    - org.gnome.font-viewer
