---
- name: "Install packages"
  become: yes
  notify:
    - "rpm-ostree apply-live"
  community.general.rpm_ostree_pkg:
    state: present
    name:
      - vim
      - ansible
      - podman
      - docker
      - docker-compose
      - git
      - htop
      - iotop
      - wl-clipboard
      - sway
      - kitty
      - swaybg
      - swayidle
      - swaylock 
      - waybar 
      - xdg-desktop-portal-wlr 
      - mako 
      - grim 
      - slurp 
      - wofi
      - fish
      - playerctl
      - wireguard-tools
      - jq
      - snapper
      - libvirt-daemon-config-network
      - virt-manager
      - virt-install
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer

