#!/bin/bash
set -e

echo "Setting up the battle station..."
echo "What is this system's hostname? Something poisonous, I hope."

read -e -p "Hostname: " -i $(hostname) hostname

echo "Setting hostname to $hostname"
echo $hostname | sudo tee /etc/hostname
sudo hostname $hostname
echo "The hostname has been set!"

echo "Installing Ansible..."

rpm-ostree install ansible || true
sudo rpm-ostree ex apply-live || true

echo "Kicking Ansible off..."

ansible-playbook -K workstation.yml -l $hostname

echo "Ansible has finished its work. Cut the power..."

