---
- name: "Enable Docker"
  become: yes
  systemd:
      name: docker
      enabled: yes
      state: started

- name: "Enable SSH"
  become: yes
  systemd:
      name: sshd
      enabled: yes
      state: started

- name: "Enable Snapper"
  become: yes
  systemd:
      name: "snapper-timeline.timer"
      enabled: yes
      state: started

      
