---
- name: "Enable Docker"
  become: yes
  systemd:
      name: docker
      enabled: yes
      state: started

- name: "Enable SSH"
  become: yes
  systemd:
      name: sshd
      enabled: yes
      state: started

- name: "Enable SSH Agent"
  systemd:
      name: ssh-agent
      enabled: yes
      state: started
      scope: user
